version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - proxynet
  db:
    image: postgres:14.5
    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db.dev
      
volumes:
  postgres_data:
  static_volume:

networks:
  proxynet:
    external: true