version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ./entrypoint.sh
    command: daphne -b 0.0.0.0 -p 8000 django_project.asgi:application
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod

  db:
    image: postgres:14.5
    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db.prod
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data:
  static_volume:
