version: '3.7'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn -b "0.0.0.0:8000" -w 3 footy_world_xi_validator.wsgi
    volumes:
      - .:/code
    ports:
      - 8080:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:12.1
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: