version: '3.9'

services:
  db:
    image: postgres:14.5
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db.dev
    networks:
      - proxynet
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/code
    command: ["sh", "-c", "pip install debugpy -t /tmp && python ./manage.py migrate && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 ./manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - proxynet
      
volumes:
  postgres_data:
  static_volume:

networks:
  proxynet:
    external: true