version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.1
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
      - .:/etc/nginx/conf.d
    ports:
      - 8000:80
      - 443:443
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: