version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 80:8000
    depends_on:
      - db
  db:
    image: postgres:12.1
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: