version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn -b "localhost:8000" -w 3 footy_world_xi_validator.wsgi
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:14.5
    restart: always
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db.prod
      
volumes:
  postgres_data:
  static_volume: