# Generated by Django 3.0.5 on 2020-04-23 18:54

import uuid

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClubTeam",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="FootballPlayer",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=300)),
                ("birthday", models.DateField(null=True)),
                ("alias", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="NationalTeam",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubmission",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason_incorrect", models.TextField(blank=True)),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="user_submissions",
                        to="footy_validator.FootballPlayer",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="nationalteam",
            index=models.Index(fields=["name"], name="footy_valid_name_de5a38_idx"),
        ),
        migrations.AddField(
            model_name="footballplayer",
            name="club_teams",
            field=models.ManyToManyField(
                related_name="players", to="footy_validator.ClubTeam"
            ),
        ),
        migrations.AddField(
            model_name="footballplayer",
            name="national_teams",
            field=models.ManyToManyField(
                related_name="players", to="footy_validator.NationalTeam"
            ),
        ),
        migrations.AddIndex(
            model_name="clubteam",
            index=models.Index(fields=["name"], name="footy_valid_name_379537_idx"),
        ),
        migrations.AddIndex(
            model_name="footballplayer",
            index=models.Index(
                fields=["full_name"], name="footy_valid_full_na_90842e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="footballplayer",
            index=models.Index(fields=["alias"], name="footy_valid_alias_a4f25e_idx"),
        ),
    ]
