# Generated by Django 4.1.2 on 2022-10-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footy_validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubteam',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='footballplayer',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='nationalteam',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'get_latest_by': 'modified'},
        ),
    ]
