# Generated by Django 3.0.5 on 2020-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footy_validator', '0002_usersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='reason_incorrect',
            field=models.TextField(blank=True),
        ),
    ]
