# Generated by Django 4.1.2 on 2022-11-18 17:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("footy_validator", "0003_temporarysubmissionplayers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubteam",
            name="team_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nationalteam",
            name="team_picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
