# Generated by Django 3.0.5 on 2020-04-23 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('footy_validator', '0003_usersubmission_reason_incorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
