# Generated by Django 3.0.5 on 2020-04-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footy_validator', '0004_auto_20200423_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubteam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='footballplayer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nationalteam',
            options={},
        ),
        migrations.AddIndex(
            model_name='clubteam',
            index=models.Index(fields=['name'], name='footy_valid_name_379537_idx'),
        ),
        migrations.AddIndex(
            model_name='footballplayer',
            index=models.Index(fields=['full_name'], name='footy_valid_full_na_90842e_idx'),
        ),
        migrations.AddIndex(
            model_name='footballplayer',
            index=models.Index(fields=['alias'], name='footy_valid_alias_a4f25e_idx'),
        ),
        migrations.AddIndex(
            model_name='nationalteam',
            index=models.Index(fields=['name'], name='footy_valid_name_de5a38_idx'),
        ),
    ]
