# Generated by Django 3.0.5 on 2020-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footy_validator', '0005_auto_20200423_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballplayer',
            name='times_selected',
        ),
    ]
